[package]
name = "Chaos"
version = "0.1.0"
edition = "2024"
description = "Utilitary program to snapshot Ethereum state in reth client."

[dependencies]
clap = "4.5.42"
hex = "0.4.3"
reth-db = { git = "https://github.com/paradigmxyz/reth", tag = "v1.4.8" }
serde = "1.0.219"
serde_json = "1.0.143"
